# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkregistry',
            name='chunk_hash',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='chunkregistry',
            name='chunk_path',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunkregistry',
            name='data_type',
            field=models.CharField(choices=[(b'stuff', b'things')], db_index=True, default='stuff', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunkregistry',
            name='is_chunkable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunkregistry',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='chunk_registries', to='study.Participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunkregistry',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='chunk_registries', to='study.Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunkregistry',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='chunk_registries', to='study.Survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunkregistry',
            name='time_bin',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 9, 8, 7, 6, 5)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetoprocess',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='files_to_process', to='study.Participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetoprocess',
            name='s3_file_path',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetoprocess',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='files_to_process', to='study.Study'),
            preserve_default=False,
        ),
    ]
