# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('mark', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
