# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20170906_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesettings',
            name='consent_sections',
            field=study.models.JSONTextField(default=b'{"study_tasks": {"text": "", "more": ""}, "data_use": {"text": "", "more": ""}, "withdrawing": {"text": "", "more": ""}, "privacy": {"text": "", "more": ""}, "study_survey": {"text": "", "more": ""}, "welcome": {"text": "", "more": ""}, "data_gathering": {"text": "", "more": ""}, "time_commitment": {"text": "", "more": ""}}'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='os_type',
            field=models.CharField(choices=[(b'IOS', b'IOS'), (b'ANDROID', b'ANDROID')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='content',
            field=study.models.JSONTextField(default='[]', help_text='JSON blob containing information about the survey questions.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='settings',
            field=study.models.JSONTextField(default='{}', help_text='JSON blob containing settings for the survey.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[(b'audio_survey', b'audio_survey'), (b'tracking_survey', b'tracking_survey')], max_length=16),
        ),
        migrations.AlterField(
            model_name='survey',
            name='timings',
            field=study.models.JSONTextField(default=b'[[], [], [], [], [], [], []]', help_text='JSON blob containing the times at which the survey is sent.'),
        ),
    ]
