# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20170908_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkregistry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filetoprocess',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
