# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_fileprocesslock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileprocesslock',
            old_name='mark',
            new_name='lock_time',
        ),
    ]
