# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import study.validators


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20170908_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='object_id',
            field=models.CharField(default="not implemented yet :'-(", help_text='ID used for naming S3 files', max_length=24, unique=True, validators=[study.validators.LengthValidator(24)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chunkregistry',
            name='data_type',
            field=models.CharField(choices=[(b'accelerometer', b'accelerometer'), (b'bluetooth', b'bluetooth'), (b'calls', b'calls'), (b'gps', b'gps'), (b'identifiers', b'identifiers'), (b'app_log', b'app_log'), (b'power_state', b'power_state'), (b'survey_answers', b'survey_answers'), (b'survey_timings', b'survey_timings'), (b'texts', b'texts'), (b'audio_recordings', b'audio_recordings'), (b'wifi', b'wifi'), (b'proximity', b'proximity'), (b'gyro', b'gyro'), (b'magnetometer', b'magnetometer'), (b'devicemotion', b'devicemotion'), (b'reachability', b'reachability')], max_length=32),
        ),
        migrations.AlterField(
            model_name='chunkregistry',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chunk_registries', to='study.Survey'),
        ),
        migrations.AlterField(
            model_name='chunkregistry',
            name='time_bin',
            field=models.DateTimeField(),
        ),
    ]
