# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 12:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20170907_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=44, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+$')])),
                ('salt', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+$')])),
                ('username', models.CharField(max_length=32, unique=True)),
                ('admin', models.BooleanField(default=False, help_text='Whether the researcher is also an admin')),
                ('access_key_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z+/]+$')])),
                ('access_key_secret', models.CharField(max_length=44, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+$')])),
                ('access_key_secret_salt', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+$')])),
                ('studies', models.ManyToManyField(related_name='researchers', to='study.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='admin',
            name='studies',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
