# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20170913_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocesslock',
            name='is_actual_lock',
            field=models.BooleanField(default=True, help_text=b'This is True if the Lock is actually a lock', unique=True),
            preserve_default=False,
        ),
    ]
