# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20170908_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkregistry',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chunk_registries', to='study.Survey'),
        ),
    ]
