# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 14:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20170907_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='os_type',
            field=models.CharField(choices=[(b'IOS', b'IOS'), (b'ANDROID', b'ANDROID')], help_text='The type of device the participant is using, if any.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(help_text="A hash of the user's password", max_length=44, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='password',
            field=models.CharField(help_text="A hash of the user's password", max_length=44, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='username',
            field=models.CharField(help_text='User-chosen username, stored in plain text', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='encryption_key',
            field=models.CharField(help_text='Key used for encrypting the study data', max_length=32),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[(b'audio_survey', b'audio_survey'), (b'tracking_survey', b'tracking_survey')], help_text='What type of survey this is.', max_length=16),
        ),
    ]
