# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import study.validators


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20170908_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='object_id',
            field=models.CharField(default="already implemented :'-)", max_length=24, unique=True, validators=[study.validators.LengthValidator(24)]),
            preserve_default=False,
        ),
    ]
