# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import study.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_remove_fileprocesslock_is_actual_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptionKeyError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=256)),
                ('contents', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decryption_key_errors', to='study.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncryptionErrorMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=256)),
                ('total_lines', models.PositiveIntegerField()),
                ('number_errors', models.PositiveIntegerField()),
                ('errors_lines', study.base_models.JSONTextField()),
                ('error_types', study.base_models.JSONTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineEncryptionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(b'AES_KEY_BAD_LENGTH', b'AES_KEY_BAD_LENGTH'), (b'EMPTY_KEY', b'EMPTY_KEY'), (b'INVALID_LENGTH', b'INVALID_LENGTH'), (b'IV_BAD_LENGTH', b'IV_BAD_LENGTH'), (b'IV_MISSING', b'IV_MISSING'), (b'LINE_EMPTY', b'LINE_EMPTY'), (b'LINE_EMPTY', b'LINE_EMPTY'), (b'MP4_PADDING', b'MP4_PADDING'), (b'MALFORMED_CONFIG', b'MALFORMED_CONFIG'), (b'PADDING_ERROR', b'PADDING_ERROR')], max_length=32)),
                ('line', models.TextField(blank=True)),
                ('base64_decryption_key', models.CharField(max_length=256)),
                ('prev_line', models.TextField(blank=True)),
                ('next_line', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=256)),
                ('file_size', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_trackers', to='study.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
