# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_decryptionkeyerror_encryptionerrormetadata_lineencryptionerror_uploadtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkregistry',
            name='chunk_path',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
