# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_survey_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='access_key_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z+/]+={0,2}$')]),
        ),
    ]
