# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import study.validators


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20170907_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='device_id',
            field=models.CharField(blank=True, default='', help_text='The ID of the device that the participant is using for the study, if any', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='os_type',
            field=models.CharField(blank=True, choices=[(b'IOS', b'IOS'), (b'ANDROID', b'ANDROID'), (b'', b'')], default='', help_text='The type of device the participant is using, if any.', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(help_text="A hash of the user's password", max_length=44, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='patient_id',
            field=models.CharField(help_text='Eight-character unique ID with characters chosen from 1-9 and a-z', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(b'^[1-9a-z]+$', message=b'This field can only contain characters 1-9 and a-z.')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='salt',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='access_key_id',
            field=models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z+/]+={0,2}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researcher',
            name='access_key_secret',
            field=models.CharField(blank=True, default='', max_length=44, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]+={0,2}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researcher',
            name='access_key_secret_salt',
            field=models.CharField(blank=True, default='', max_length=24, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]+={0,2}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researcher',
            name='password',
            field=models.CharField(help_text="A hash of the user's password", max_length=44, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='salt',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='study',
            name='encryption_key',
            field=models.CharField(help_text='Key used for encrypting the study data', max_length=32, validators=[study.validators.LengthValidator(32)]),
        ),
    ]
