# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20170907_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='device_id',
            field=models.CharField(blank=True, help_text='The ID of the device that the participant is using for the study, if any.', max_length=256),
        ),
    ]
