# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180320_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
