# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 16:14
from __future__ import unicode_literals

from django.db import migrations


def add_admin_user_if_not_exists(apps, schema_editor):
    Researcher = apps.get_model('database', 'Researcher')
    if Researcher.objects.filter(admin=True).count == 0:
        r = Researcher.create_without_password()
        r.admin = True
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_study_is_test'),
    ]

    operations = [
        migrations.RunPython(add_admin_user_if_not_exists)
    ]
